### ISSUE TITLE
Version with Scalaz

### ISSUE THREAD

**Issue by jdegoes** [zio/interop-scalaz#1]
I think we should version this library with Scalaz.

e.g. if you're using Scalaz 7.3, then you pull in `interop-scalaz` 7.3.

We can use the micro version for backward-compatible updates within a Scalaz version.

Thoughts?

**Comment by mijicd** [comment]
As agreed in `ZIO/Core` gitter, we'll proceed with `vA.B.C.D` versioning scheme, `A.B.C` coming representing semantic version of a library, and `D` enumerating the patch made in interop.
